<definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" name="hello" targetNamespace="hello">
<message name="sayHelloResponse1">
<part name="greeting" type="xsd:string"/>
</message>
<message name="sayHelloRequest1">
<part name="name" type="xsd:string"/>
</message>
<portType name="helloPortType">
<operation name="sayHello" parameterOrder="name">
<input message="sayHelloRequest1"/>
<output message="sayHelloResponse1"/>
</operation>
</portType>
<binding name="helloBinding" type="helloPortType">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="sayHello">
<soap:operation soapAction="urn:HelloServer#sayHello"/>
<input>
<soap:body use="encoded" namespace="urn:HelloServer" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</input>
<output>
<soap:body use="encoded" namespace="urn:HelloServer" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
</output>
</operation>
</binding>
<service name="helloService">
<port name="helloPort" binding="helloBinding">
<soap:address location="http://geneura.ugr.es/cgi-bin/pedro/helloworld_cgi_serv.cgi"/>
</port>
</service>
</definitions>